
stages:
  - build
  - test
  - pages

build_release_focal:
  image: aocompass/base-20.04:11.8.0
  stage: build
  variables:
    COMPASS_ROOT: /builds/compass/compass
    SHESHA_ROOT: $COMPASS_ROOT/shesha
    COMPASS_DO_HALF: "OFF"
  script:
    - export PYTHONPATH=$SHESHA_ROOT:$COMPASS_ROOT/local/python:$PYTHONPATH
    - export LD_LIBRARY_PATH=$COMPASS_ROOT/local/lib:$LD_LIBRARY_PATH
    - ./script/install_conan_gcc.sh
    - ./compile.sh $PWD/local
  when: manual
  # only:
  #  - develop
  artifacts:
    paths:
      - local/
    expire_in: 1 week

build_release_main_focal:
  image: aocompass/base-20.04:11.8.0
  extends: build_release_focal
  stage: build
  when: always
  only:
    - main
    - rc
    - tags

build_debug_focal:
  image: aocompass/base-20.04:11.8.0
  stage: build
  variables:
    COMPASS_ROOT: /builds/compass/compass
    SHESHA_ROOT: $COMPASS_ROOT/shesha
    COMPASS_DEBUG: "-DCMAKE_BUILD_TYPE=Debug"
    COMPASS_DO_HALF: "OFF"
  script:
    - export PYTHONPATH=$SHESHA_ROOT:$COMPASS_ROOT/local/python:$PYTHONPATH
    - export LD_LIBRARY_PATH=$COMPASS_ROOT/local/lib:$LD_LIBRARY_PATH
    - ./script/install_conan_gcc.sh
    - pip install -r script/requirements.txt
    - pip install -r script/requirements-dev.txt
    - ./compile.sh $PWD/local
  when: always
  only:
    - merge_requests
    - develop
  artifacts:
    paths:
      - local/
    expire_in: 1 week

test_debug_focal:
  image: aocompass/base-20.04:11.8.0
  stage: test
  dependencies:
    - build_debug_focal
  variables:
    COMPASS_ROOT: /builds/compass/compass
    SHESHA_ROOT: $COMPASS_ROOT/shesha
    NAGA_ROOT: $COMPASS_ROOT/naga
  script:
    - export PYTHONPATH=$NAGA_ROOT:$SHESHA_ROOT:$NAGA_ROOT:$COMPASS_ROOT/local/python:$PYTHONPATH
    - export LD_LIBRARY_PATH=$COMPASS_ROOT/local/lib:$LD_LIBRARY_PATH
    - pip install -r script/requirements.txt
    - pip install -r script/requirements-test.txt
    - $COMPASS_ROOT/shesha/tests/checkCompass.sh 
    - $COMPASS_ROOT/doc/generate_coverage.sh
    - coverage report
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    paths:
      - .coverage
      - report_E2E.md
    expire_in: 1 week
  when: always
  only:
    - merge_requests
    - develop

test_main_focal:
  image: aocompass/base-20.04:11.8.0
  extends: test_debug_focal
  stage: test
  dependencies:
    - build_release_main_focal
  when: always
  only:
    - main
    - rc
    - tags

pages:
  image: aocompass/base-20.04:11.8.0
  stage: pages
  variables:
    COMPASS_ROOT: /builds/compass/compass
    SHESHA_ROOT: $COMPASS_ROOT/shesha
    NAGA_ROOT: $COMPASS_ROOT/naga
  dependencies:
    - build_debug_focal
    - test_debug_focal
  script:
    - export PYTHONPATH=$SHESHA_ROOT:$NAGA_ROOT:$COMPASS_ROOT/local/python:$PYTHONPATH
    - export LD_LIBRARY_PATH=$COMPASS_ROOT/local/lib:$MAGMA_ROOT/lib:$LD_LIBRARY_PATH
    - pip install -r script/requirements.txt
    - pip install -r script/requirements-test.txt
    - pip install -r script/requirements-doc.txt
    - $COMPASS_ROOT/doc/py_filter_install.sh
    - $COMPASS_ROOT/doc/generate_stubs.sh
    - $COMPASS_ROOT/doc/generate_reports.sh
    - $COMPASS_ROOT/doc/correctDoxygen_gitlab.sh
  artifacts:
    paths:
    - public
  when: always  # manual / always
  only:
    - develop

# pages:
#   stage: deploy
#   variables:
#     COMPASS_ROOT: /builds/compass/compass
#     SHESHA_ROOT: $COMPASS_ROOT/shesha
#     NAGA_ROOT: $COMPASS_ROOT/naga
#   dependencies:
#     - pytests
#   script:
#     - pip install -r requirements-test.txt
#     - coverage html -d public
#   artifacts:
#     paths:
#     - public
#   when: always
#   only:
#     - develop

build_release_jammy:
  image: aocompass/base-22.04:11.8.0
  stage: build
  variables:
    COMPASS_ROOT: /builds/compass/compass
    SHESHA_ROOT: $COMPASS_ROOT/shesha
    COMPASS_DO_HALF: "OFF"
  script:
    - export PYTHONPATH=$SHESHA_ROOT:$COMPASS_ROOT/local/python:$PYTHONPATH
    - export LD_LIBRARY_PATH=$COMPASS_ROOT/local/lib:$LD_LIBRARY_PATH
    - ./script/install_conan_gcc.sh
    - ./compile.sh $PWD/local
  when: manual
  # only:
  #  - develop
  artifacts:
    paths:
      - local/
    expire_in: 1 week

build_release_main_jammy:
  image: aocompass/base-22.04:11.8.0
  extends: build_release_jammy
  stage: build
  when: always
  only:
    - main
    - rc
    - tags

build_debug_jammy:
  image: aocompass/base-22.04:11.8.0
  stage: build
  variables:
    COMPASS_ROOT: /builds/compass/compass
    SHESHA_ROOT: $COMPASS_ROOT/shesha
    COMPASS_DEBUG: "-DCMAKE_BUILD_TYPE=Debug"
    COMPASS_DO_HALF: "OFF"
  script:
    - export PYTHONPATH=$SHESHA_ROOT:$COMPASS_ROOT/local/python:$PYTHONPATH
    - export LD_LIBRARY_PATH=$COMPASS_ROOT/local/lib:$LD_LIBRARY_PATH
    - ./script/install_conan_gcc.sh
    - pip install -r script/requirements.txt
    - pip install -r script/requirements-dev.txt
    - ./compile.sh $PWD/local
  when: always
  only:
    - merge_requests
    - develop
  artifacts:
    paths:
      - local/
    expire_in: 1 week

test_debug_jammy:
  image: aocompass/base-22.04:11.8.0
  stage: test
  dependencies:
    - build_debug_jammy
  variables:
    COMPASS_ROOT: /builds/compass/compass
    SHESHA_ROOT: $COMPASS_ROOT/shesha
    NAGA_ROOT: $COMPASS_ROOT/naga
  script:
    - export PYTHONPATH=$NAGA_ROOT:$SHESHA_ROOT:$NAGA_ROOT:$COMPASS_ROOT/local/python:$PYTHONPATH
    - export LD_LIBRARY_PATH=$COMPASS_ROOT/local/lib:$LD_LIBRARY_PATH
    - pip install -r script/requirements.txt
    - pip install -r script/requirements-test.txt
    - $COMPASS_ROOT/shesha/tests/checkCompass.sh 
    - $COMPASS_ROOT/doc/generate_coverage.sh
    - coverage report
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    paths:
      - .coverage
      - report_E2E.md
    expire_in: 1 week
  when: always
  only:
    - merge_requests
    - develop

test_main_jammy:
  image: aocompass/base-22.04:11.8.0
  extends: test_debug_jammy
  stage: test
  dependencies:
    - build_release_main_jammy
  when: always
  only:
    - main
    - rc
    - tags


build_release_rockylinux8:
  image: aocompass/base-rockylinux8:11.8.0
  stage: build
  variables:
    COMPASS_ROOT: /builds/compass/compass
    SHESHA_ROOT: $COMPASS_ROOT/shesha
    COMPASS_DO_HALF: "OFF"
  script:
    - export PYTHONPATH=$SHESHA_ROOT:$COMPASS_ROOT/local/python:$PYTHONPATH
    - export LD_LIBRARY_PATH=$COMPASS_ROOT/local/lib:$LD_LIBRARY_PATH
    - ./script/install_conan_gcc.sh
    - ./compile.sh $PWD/local
  when: manual
  # only:
  #  - develop
  artifacts:
    paths:
      - local/
    expire_in: 1 week

build_release_main_rockylinux8:
  image: aocompass/base-rockylinux8:11.8.0
  extends: build_release_rockylinux8
  stage: build
  when: always
  only:
    - main
    - rc
    - tags

build_debug_rockylinux8:
  image: aocompass/base-rockylinux8:11.8.0
  stage: build
  variables:
    COMPASS_ROOT: /builds/compass/compass
    SHESHA_ROOT: $COMPASS_ROOT/shesha
    COMPASS_DEBUG: "-DCMAKE_BUILD_TYPE=Debug"
    COMPASS_DO_HALF: "OFF"
  script:
    - export PYTHONPATH=$SHESHA_ROOT:$COMPASS_ROOT/local/python:$PYTHONPATH
    - export LD_LIBRARY_PATH=$COMPASS_ROOT/local/lib:$LD_LIBRARY_PATH
    - ./script/install_conan_gcc.sh
    - pip install -r script/requirements.txt
    - pip install -r script/requirements-dev.txt
    - ./compile.sh $PWD/local
  when: always
  only:
    - merge_requests
    - develop
  artifacts:
    paths:
      - local/
    expire_in: 1 week

test_debug_rockylinux8:
  image: aocompass/base-rockylinux8:11.8.0
  stage: test
  dependencies:
    - build_debug_rockylinux8
  variables:
    COMPASS_ROOT: /builds/compass/compass
    SHESHA_ROOT: $COMPASS_ROOT/shesha
    NAGA_ROOT: $COMPASS_ROOT/naga
  script:
    - export PYTHONPATH=$NAGA_ROOT:$SHESHA_ROOT:$NAGA_ROOT:$COMPASS_ROOT/local/python:$PYTHONPATH
    - export LD_LIBRARY_PATH=$COMPASS_ROOT/local/lib:$LD_LIBRARY_PATH
    - pip install -r script/requirements.txt
    - pip install -r script/requirements-test.txt
    - $COMPASS_ROOT/shesha/tests/checkCompass.sh 
    - $COMPASS_ROOT/doc/generate_coverage.sh
    - coverage report
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    paths:
      - .coverage
      - report_E2E.md
    expire_in: 1 week
  when: always
  only:
    - merge_requests
    - develop

test_main_rockylinux8:
  image: aocompass/base-rockylinux8:11.8.0
  extends: test_debug_rockylinux8
  stage: test
  dependencies:
    - build_release_main_rockylinux8
  when: always
  only:
    - main
    - rc
    - tags

