image: sevin/compass:cuda8

stages:
  - build
#  - test
#  - deploy

master_build:
  stage: build
  script:
    - make
#   - cd doc
#   - mkdir -p compass-doc/html
#   - make html
#   - mv compass-doc/html/ public/
# artifacts:
#   paths:
#   - public
  only:
    - master
#    - tags
#    - develop

develop_build:
  stage: build
  script:
    - make
#   - cd doc
#   - mkdir -p compass-doc/html
#   - make html
#   - mv compass-doc/html/ public/
# artifacts:
#   paths:
#   - public
  when: manual
  only:
    - develop
