image: aocompass/base-devel-16.04

stages:
  - build
  - test
#  - deploy

build_job:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    COMPASS_ROOT: /builds/compass/compass
    SHESHA_ROOT: $COMPASS_ROOT/shesha
    CUDA_SM: ALL
  script:
    - export PYTHONPATH=$SHESHA_ROOT:$COMPASS_ROOT/python:$PYTHONPATH
    - mkdir -p python
    - easy_install -d python .
  when: manual
  only:
    - develop
  artifacts:
    paths:
      - python/
    expire_in: 1 week

master_build:
  stage: build
  extends: build_job
  when: always
  only:
    - master
    - tags

test_job:
  stage: test
  variables:
    COMPASS_ROOT: /builds/compass/compass
    SHESHA_ROOT: $COMPASS_ROOT/shesha
  dependencies:
    - build_job
  script:
    - export PYTHONPATH=$SHESHA_ROOT:$COMPASS_ROOT/python:$PYTHONPATH
    - export LD_LIBRARY_PATH=$COMPASS_ROOT/python/compass_sim-4.0.0-py3.7-linux-x86_64.egg:$LD_LIBRARY_PATH
    - cd shesha && python shesha/scripts/closed_loop.py data/par/par4bench/scao_sh_16x16_8pix.py
    - cd shesha/tests && . checkCompass.sh
  when: manual
  only:
    - develop

master_tests:
  stage: test
  extends: test_job
  dependencies:
    - master_build
  when: always
  only:
    - master
    - tags
