image: aocompass/base-18.04:10.2

stages:
  - build
  - test
  - deploy

build_release:
  stage: build
  variables:
    COMPASS_ROOT: /builds/compass/compass
    SHESHA_ROOT: $COMPASS_ROOT/shesha
  script:
    - export CUDA_ROOT=/usr/local/cuda
    - export COMPASS_DO_HALF="OFF"
    - export PYTHONPATH=$SHESHA_ROOT:$COMPASS_ROOT/local/python:$PYTHONPATH
    - export LD_LIBRARY_PATH=$COMPASS_ROOT/local/lib:$LD_LIBRARY_PATH
    - ./script/install_conan.sh 8
    - pip install -r script/requirements.txt
    - ./compile.sh $PWD/local
  when: manual
  # only:
  #  - develop
  artifacts:
    paths:
      - local/
    expire_in: 1 week

build_release_main:
  stage: build
  extends: build_release
  when: always
  only:
    - main
    - rc
    - tags

build_debug:
  stage: build
  variables:
    COMPASS_ROOT: /builds/compass/compass
    SHESHA_ROOT: $COMPASS_ROOT/shesha
    COMPASS_DEBUG: "-DCMAKE_BUILD_TYPE=Debug"
    COMPASS_DO_HALF: "OFF"
  script:
    - export CUDA_ROOT=/usr/local/cuda
    - export PYTHONPATH=$SHESHA_ROOT:$COMPASS_ROOT/local/python:$PYTHONPATH
    - export LD_LIBRARY_PATH=$COMPASS_ROOT/local/lib:$LD_LIBRARY_PATH
    - ./script/install_conan.sh 8
    - pip install -r script/requirements.txt
    - ./compile.sh $PWD/local
  when: always
  only:
    - merge_requests
    - develop
  artifacts:
    paths:
      - local/
    expire_in: 1 week

pytests:
  stage: test
  variables:
    COMPASS_ROOT: /builds/compass/compass
    SHESHA_ROOT: $COMPASS_ROOT/shesha
    NAGA_ROOT: $COMPASS_ROOT/naga
  dependencies:
    - build_debug
  script:
    - export PYTHONPATH=$NAGA_ROOT:$SHESHA_ROOT:$NAGA_ROOT:$COMPASS_ROOT/local/python:$PYTHONPATH
    - export LD_LIBRARY_PATH=$COMPASS_ROOT/local/lib:$LD_LIBRARY_PATH
    - pip install -r script/requirements.txt
    - pip install -r script/requirements-test.txt
    - $COMPASS_ROOT/doc/generate_coverage.sh
    - coverage report
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    paths:
      - .coverage
    expire_in: 1 week
  when: always
  only:
    - merge_requests
    - develop

main_pytests:
  stage: test
  extends: pytests
  dependencies:
    - build_release_main
  when: always
  only:
    - main
    - rc
    - tags

pages:
  stage: deploy
  variables:
    COMPASS_ROOT: /builds/compass/compass
    SHESHA_ROOT: $COMPASS_ROOT/shesha
    NAGA_ROOT: $COMPASS_ROOT/naga
  dependencies:
    - build_debug
    - pytests
  script:
    - export PYTHONPATH=$SHESHA_ROOT:$NAGA_ROOT:$COMPASS_ROOT/local/python:$PYTHONPATH
    - export LD_LIBRARY_PATH=$COMPASS_ROOT/local/lib:$MAGMA_ROOT/lib:$LD_LIBRARY_PATH
    - pip install -r script/requirements.txt
    - pip install -r script/requirements-test.txt
    - pip install -r script/requirements-doc.txt
    - $COMPASS_ROOT/doc/generate_stubs.sh
    - $COMPASS_ROOT/doc/generate_reports.sh
    - $COMPASS_ROOT/doc/correctDoxygen_gitlab.sh
  artifacts:
    paths:
    - public
  when: always  # manual / always
  only:
    - develop

# pages:
#   stage: deploy
#   variables:
#     COMPASS_ROOT: /builds/compass/compass
#     SHESHA_ROOT: $COMPASS_ROOT/shesha
#     NAGA_ROOT: $COMPASS_ROOT/naga
#   dependencies:
#     - pytests
#   script:
#     - pip install -r requirements-test.txt
#     - coverage html -d public
#   artifacts:
#     paths:
#     - public
#   when: always
#   only:
#     - develop
