image: aocompass/base-devel-16.04:10.0

stages:
  - build
  - test
#  - deploy

build_job:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    COMPASS_ROOT: /builds/compass/compass
    SHESHA_ROOT: $COMPASS_ROOT/shesha
    CUB_ROOT: $COMPASS_ROOT/tplib/cub
    WYRM_ROOT: $COMPASS_ROOT/tplib/wyrm
    CUDA_SM: ALL
    # COMPASS_DO_HALF: "ON"
  script:
    - export PYTHONPATH=$SHESHA_ROOT:$COMPASS_ROOT/local/python:$PYTHONPATH
    - export LD_LIBRARY_PATH=$COMPASS_ROOT/local/lib:$LD_LIBRARY_PATH
    - ./compile.sh
  when: manual
  only:
    - develop
  artifacts:
    paths:
      - local/
    expire_in: 1 week

master_build:
  stage: build
  extends: build_job
  when: always
  only:
    - master
    - tags

test_job:
  stage: test
  variables:
    COMPASS_ROOT: /builds/compass/compass
    SHESHA_ROOT: $COMPASS_ROOT/shesha
  dependencies:
    - build_job
  script:
    - export PYTHONPATH=$SHESHA_ROOT:$COMPASS_ROOT/local/python:$PYTHONPATH
    - export LD_LIBRARY_PATH=$COMPASS_ROOT/local/lib:$LD_LIBRARY_PATH
    - pytest libcarma/python_module/test
    - pip install tabulate
    - ./shesha/tests/checkCompass.sh

  when: manual
  only:
    - develop

master_tests:
  stage: test
  extends: test_job
  dependencies:
    - master_build
  when: always
  only:
    - master
    - tags
