image: sevin/compass:cuda9

stages:
  - build
#  - test
#  - deploy

master_build:
  stage: build
  variables:
    COMPASS_ROOT: /builds/compass/compass
    NAGA_ROOT: $COMPASS_ROOT/naga
    SHESHA_ROOT: $COMPASS_ROOT/shesha
  script:
    - make
#   - cd doc
#   - mkdir -p compass-doc/html
#   - make html
#   - mv compass-doc/html/ public/
# artifacts:
#   paths:
#   - public
  only:
    - master
#    - tags
#    - develop

develop_build:
  stage: build
  variables:
    COMPASS_ROOT: /builds/compass/compass
    NAGA_ROOT: $COMPASS_ROOT/naga
    SHESHA_ROOT: $COMPASS_ROOT/shesha
  script:
    - make
#   - cd doc
#   - mkdir -p compass-doc/html
#   - make html
#   - mv compass-doc/html/ public/
# artifacts:
#   paths:
#   - public
  when: manual
  only:
    - develop
