repos:
-   repo: https://github.com/pre-commit/mirrors-yapf.git
    sha: v0.24.0
    hooks:
    -   id: yapf
-   repo: https://github.com/pre-commit/mirrors-autopep8
    sha: v1.4.2
    hooks:
    -   id: autopep8
        files: \.pyx
        args:
        - --in-place
        - --max-line-length
        - '80'
        - -a
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v2.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: \.fits
    -   id: end-of-file-fixer
        exclude: \.fits
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
#-   repo: local
#    hooks:
#    -   id: cpp-cuda-linter
#        name: cpp-pre-commit
#        entry: ./apply-format -i
#        language: system
#        files: \.(cu|hpp|cuh|h|cpp|c)
