name: compass
channels:
  - conda-forge
dependencies:
  - python<3.12
  - astropy
  - docopt
  - h5py
  - ipython
  - matplotlib
  - numpy
  - pandas
  - pyqtgraph
  - scipy
  - pytables
  - tabulate
  - rich
  - aenum
  - cmake
  - coverage
  - pytest-cov
  - pytest-html
  - pytest-metadata
  - ruff