name: compass
channels:
  - conda-forge
dependencies:
  - pip
  - python
  - astropy
  - docopt
  - h5py
  - ipython
  - matplotlib
  - numpy
  - pandas
  - scipy
  - pytables
  - tabulate
  - rich
  - aenum
  - cmake
  - pybind11
  - coverage
  - pytest-cov
  - pytest-html
  - pytest-metadata
  - ruff
  - pip:
    - pyqt6
    - pyqtgraph